import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google"; // 追加

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  //メタ情報(SEO対策)
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className="bg-red-300 p-4">ヘッダー</div>
        {children}
      </body>
    </html>
  );
}
